import { useMemo, useState } from 'react';
import { Calculator, CalendarDays, RotateCcw, Scale, WalletCards } from 'lucide-react';
import { calculateCase, formatSentence, formatThaiDate, type CalculationMode } from './engine';

const today = () => new Date().toISOString().slice(0, 10);
const money = (n: number) => `${Math.round(n).toLocaleString('th-TH')} บาท`;
const Field = ({label, hint, children}:{label:string;hint?:string;children:React.ReactNode}) => <label className="field"><span className="field-label">{label}</span>{children}{hint&&<small>{hint}</small>}</label>;
const Result = ({label,value,hot=false}:{label:string;value:string;hot?:boolean}) => <div className={`result ${hot?'result-hi':''}`}><span>{label}</span><strong>{value}</strong></div>;

export default function AppV2(){
 const [mode,setMode]=useState<CalculationMode>('fine');
 const [sentence,setSentence]=useState({years:0,months:0,days:0});
 const [judgmentDate,setJudgmentDate]=useState('');
 const [pretrialDays,setPretrialDays]=useState(0);
 const [imprisonmentStart,setImprisonmentStart]=useState('');
 const [fineAmount,setFineAmount]=useState(100000),[paidBefore,setPaidBefore]=useState(0),[paidToday,setPaidToday]=useState(0),[rate,setRate]=useState(500);
 const [confinementStart,setConfinementStart]=useState(''),[checkDate,setCheckDate]=useState(today()),[maxConfinementYears,setMaxConfinementYears]=useState<1|2>(1);
 const needsPrison=mode!=='fine',needsConfinement=mode==='fine'||mode==='imprisonConfinement';
 const result=useMemo(()=>calculateCase({mode,sentence,pretrialDays,imprisonmentStart,fineAmount,paidBefore,paidToday,fineRate:rate,confinementStart,checkDate,maxConfinementYears}),[mode,sentence,pretrialDays,imprisonmentStart,fineAmount,paidBefore,paidToday,rate,confinementStart,checkDate,maxConfinementYears]);
 const setPart=(k:'years'|'months'|'days',v:string)=>setSentence(s=>({...s,[k]:Math.max(0,Number(v)||0)}));
 const reset=()=>{setMode('fine');setSentence({years:0,months:0,days:0});setJudgmentDate('');setPretrialDays(0);setImprisonmentStart('');setFineAmount(100000);setPaidBefore(0);setPaidToday(0);setRate(500);setConfinementStart('');setCheckDate(today());setMaxConfinementYears(1)};
 const modes:[CalculationMode,string,string][]=[['fine','กักขังแทนค่าปรับ','คำนวณวันกักขังจากค่าปรับ'],['imprisonFine','จำคุกและปรับ','จำคุกพร้อมค่าปรับ'],['imprisonConfinement','จำคุกและกักขังแทนค่าปรับ','จำคุก + กักขังแทนค่าปรับ']];
 const startLabel=mode==='fine'?'วันเริ่มกักขัง':'วันเริ่มจำคุก';
 return <div className="app-shell"><header className="hero"><div className="hero-inner"><div className="brand"><div className="brand-icon"><Scale size={25}/></div><div><div className="eyebrow">LEGAL CALCULATION SYSTEM</div><h1>ระบบคำนวณวันต้องโทษ <b>V2</b></h1><p>Calculation Engine เดียวสำหรับทั้ง 3 กรณี</p></div></div><button className="reset-btn" onClick={reset}><RotateCcw size={16}/>เริ่มคำนวณใหม่</button></div></header>
 <main className="workspace"><section className="step-card"><div className="section-title"><div className="step-no">01</div><div><h2>เลือกประเภทการคำนวณ</h2><p>เลือกให้ตรงกับคำพิพากษาหรือกรณีที่ต้องการตรวจสอบ</p></div></div><div className="mode-grid">{modes.map(([v,t,d])=><button key={v} className={`mode-card ${mode===v?'selected':''}`} onClick={()=>setMode(v)}><span className="mode-check">{mode===v?'✓':''}</span><strong>{t}</strong><small>{d}</small></button>)}</div></section>
 {needsPrison&&<section className="step-card"><div className="section-title"><div className="step-no">02</div><div><h2>ข้อมูลโทษจำคุก</h2><p>ระบุระยะโทษตามคำพิพากษา และวันพิพากษา/วันเริ่มจำคุก</p></div></div><div className="input-panel"><div className="panel-label">ระยะเวลาจำคุก</div><div className="sentence-grid"><Field label="ปี"><input type="number" min="0" value={sentence.years} onChange={e=>setPart('years',e.target.value)}/></Field><Field label="เดือน"><input type="number" min="0" max="11" value={sentence.months} onChange={e=>setPart('months',e.target.value)}/></Field><Field label="วัน"><input type="number" min="0" value={sentence.days} onChange={e=>setPart('days',e.target.value)}/></Field></div></div><div className="grid-two"><Field label="วันพิพากษา"><div className="date-wrap"><CalendarDays size={18}/><input type="date" value={judgmentDate} onChange={e=>setJudgmentDate(e.target.value)}/></div></Field><Field label={startLabel}><div className="date-wrap"><CalendarDays size={18}/><input type="date" value={imprisonmentStart} onChange={e=>setImprisonmentStart(e.target.value)}/></div></Field></div></section>}
 {!needsPrison&&<section className="step-card"><div className="section-title"><div className="step-no">02</div><div><h2>วันพิพากษาและวันเริ่มกักขัง</h2><p>ระบุวันพิพากษาและวันที่เริ่มกักขังแทนค่าปรับ</p></div></div><div className="grid-two"><Field label="วันพิพากษา"><div className="date-wrap"><CalendarDays size={18}/><input type="date" value={judgmentDate} onChange={e=>setJudgmentDate(e.target.value)}/></div></Field><Field label="วันเริ่มกักขัง"><div className="date-wrap"><CalendarDays size={18}/><input type="date" value={confinementStart} onChange={e=>setConfinementStart(e.target.value)}/></div></Field></div></section>}
 <section className="step-card"><div className="section-title"><div className="step-no">{needsPrison?'03':'03'}</div><div><h2>การคุมขังก่อนพิพากษา</h2><p>กรอกจำนวนวันที่ถูกคุมขังก่อนพิพากษาเป็นตัวเลขโดยตรง</p></div></div><div className="grid-two"><Field label="จำนวนวันคุมขังก่อนพิพากษา" hint="กรอกจำนวนวันตามหมาย/หลักฐาน ไม่ต้องกรอกวันเริ่มและวันสิ้นสุด"><input type="number" min="0" step="1" inputMode="numeric" value={pretrialDays} onChange={e=>setPretrialDays(Math.max(0,Number(e.target.value)||0))}/></Field><div className="inline-info" style={{alignSelf:'end',marginBottom:0}}><CalendarDays size={16}/> คุมขังก่อนพิพากษา <b>{pretrialDays} วัน</b></div></div></section>
 <section className="step-card"><div className="section-title"><div className="step-no">04</div><div><h2>ข้อมูลค่าปรับ</h2><p>ระบุยอดตามคำพิพากษาและยอดที่ชำระแล้ว</p></div></div><div className="grid-three"><Field label="ค่าปรับตามคำพิพากษา"><div className="money-input"><input type="number" min="0" value={fineAmount} onChange={e=>setFineAmount(Math.max(0,Number(e.target.value)||0))}/><span>บาท</span></div></Field><Field label="ชำระก่อนเริ่มกักขัง"><div className="money-input"><input type="number" min="0" value={paidBefore} onChange={e=>setPaidBefore(Math.max(0,Number(e.target.value)||0))}/><span>บาท</span></div></Field><Field label="อัตราหักต่อวัน"><div className="money-input"><input type="number" min="1" value={rate} onChange={e=>setRate(Math.max(1,Number(e.target.value)||500))}/><span>บาท/วัน</span></div></Field></div><div className="fine-strip"><WalletCards size={18}/><span>ค่าปรับหลังหักเงินที่ชำระแล้ว</span><b>{money(result.fine.initialRemaining)}</b></div></section>
 {needsConfinement&&<section className="step-card"><div className="section-title"><div className="step-no">05</div><div><h2>การกักขังแทนค่าปรับ</h2><p>ตรวจสอบยอดคงเหลือและวันที่มาชำระระหว่างกักขัง</p></div></div><div className="grid-two"><Field label="วันเริ่มกักขัง"><div className="date-wrap"><CalendarDays size={18}/><input type="date" value={confinementStart} onChange={e=>setConfinementStart(e.target.value)}/></div></Field><Field label="วันที่ตรวจสอบ / วันที่มาชำระ"><div className="date-wrap"><CalendarDays size={18}/><input type="date" value={checkDate} onChange={e=>setCheckDate(e.target.value)}/></div></Field><Field label="ชำระเงินวันนี้"><div className="money-input"><input type="number" min="0" value={paidToday} onChange={e=>setPaidToday(Math.max(0,Number(e.target.value)||0))}/><span>บาท</span></div></Field><Field label="เพดานการกักขัง"><select value={maxConfinementYears} onChange={e=>setMaxConfinementYears(Number(e.target.value) as 1|2)}><option value="1">ไม่เกิน 1 ปี</option><option value="2">ไม่เกิน 2 ปี</option></select></Field></div>{result.confinement.elapsedDays>0&&<div className="inline-info"><CalendarDays size={16}/> กักขังมาแล้ว <b>{result.confinement.elapsedDays} วัน</b> • เครดิต {money(result.fine.confinementCredit)}</div>}</section>}
 <section className="summary-card"><div className="summary-head"><div><div className="eyebrow dark">CALCULATION RESULT</div><h2>ผลคำนวณจาก Engine กลาง</h2></div><span className={`status ${result.status==='PAID'?'paid':''}`}>{result.status==='PAID'?'✓ ชำระครบแล้ว':'● ยังมียอดคงเหลือ'}</span></div><div className="result-grid">{needsPrison&&<><Result label="โทษจำคุกตามคำพิพากษา" value={formatSentence(sentence)}/><Result label="วันคุมขังก่อนพิพากษา" value={`${pretrialDays} วัน`}/><Result label="หักเข้าโทษจำคุก" value={`${result.sentence.imprisonmentCreditDays} วัน`}/><Result label="เหลือหักค่าปรับ" value={`${result.sentence.remainingPretrialDays} วัน`}/></>}<Result label="ค่าปรับคงเหลือ" value={money(result.fine.remaining)} hot/><Result label="กักขังแทนค่าปรับคงเหลือ" value={needsConfinement?`${result.confinement.remainingDays} วัน`:'—'} hot/><Result label="วันพ้นโทษโดยประมาณ" value={needsConfinement?formatThaiDate(result.confinement.projectedEnd):formatThaiDate(result.sentence.projectedRelease)}/></div><div className="formula-mini"><Calculator size={16}/><span>Engine: <b>calculateCase()</b> • ทุกกรณีใช้ชุดคำนวณกลางเดียวกัน</span></div></section>
 <section className="warning">⚠️ <span><b>หมายเหตุ:</b> ระบบนี้เป็นเครื่องมือช่วยคำนวณ ต้องตรวจสอบคำพิพากษา หมายจำคุก หมายกักขัง และหลักเกณฑ์ที่ใช้บังคับก่อนนำผลไปใช้เป็นทางการ</span></section>
 </main></div>;
}